### ISSUE TITLE
None of your new APIs are actually included in the library

### ISSUE THREAD

**Issue by keithlayne** [fantasydata/fantasydata-api-node#3]
See https://github.com/fantasydata/fantasydata-api-node/blob/master/package.json#L5 - this didn't change, and neither did the entrypoint file.

https://github.com/fantasydata/fantasydata-api-node/blob/master/FantasyData.Api.Client/FantasyDataClient.js was added, but it's floating by itself and is broken.  If you tried to `require` it you'd get errors.

**Comment by ScottGimpel** [comment]
Hi Keith, we appreciate the feedback. Our node developer is out of the office for a few days, but we'll have him take a look once he returns. Apologies for the inconvenience.

**Comment by neipo13** [comment]
Hey Keith,

Great Catch. It totally worked for all the existing APIs (even if they added endpoints) but any new ones would not have been working. Updated our process to remove this as a future problem. Pushing a new version shortly.

**Comment by keithlayne** [comment]
Thanks!
